
rom_com=Genre.create("Romantic Comedy")
action=Genre.create("Action")
sci_fi=Genre.create("Science Fiction")
slasher=Genre.create("Slasher")

g1=Guest.create("Hadi")
g2=Guest.create("Donovan")
g3=Guest.create("Drake")
g4=Guest.create("Sonny")
g5=Guest.create("Shrek")
g6=Guest.create("Neo")
g7=Guest.create("Trinity")
g8=Guest.create("P.Rudd")
g9=Guest.create("Jackie Chan")
g10=Guest.create("Bagheera")

m1 = Movie.create(title: "Groundhog Day", genre: "rom_com", showtime: 6, theater: "Commando Theater")
m2 = Movie.create(title: "Clueless", genre: "rom_com", showtime: 3, theater: "Commando Theater")
m3 = Movie.create(title: "Sleepless in Seattle", genre: "rom_com", showtime: 11, theater: "Commando Theater")
m4 = Movie.create(title: "Rush Hour", genre: "action", showtime: 4, theater: "Commando Theater")
m5 = Movie.create(title: "The Matrix", genre: "action", showtime: 12, theater: "Commando Theater")
m6 = Movie.create(title: "Inside Man", genre: "action", showtime: 6, theater: "Commando Theater")
m7 = Movie.create(title: "Mars Attacks", genre: "sci_fi", showtime: 9, theater: "Commando Theater")
m8 = Movie.create(title: "Predator", genre: "sci_fi", showtime: 12, theater: "Commando Theater")
m9 = Movie.create(title: "Jurassic Park", genre: "sci_fi", showtime: 4, theater: "Commando Theater")
m10 = Movie.create(title: "I Know What You Did Last Summer", genre: "slasher", showtime: 11, theater: "Commando Theater")
m11 = Movie.create(title: "Scream", genre: "slasher", showtime: 12, theater: "Commando Theater")
m12 = Movie.create(title: "Halloween", genre: "slasher", showtime: 10, theater: "Commando Theater")

commando=Theater.create(name: "Commando Theater")

t1=Ticket.create(theater: "Commando Theater", movie: "Groundhog Day", guest: "Bagheera")
t2=Ticket.create(theater: "Commando Theater", movie: "Clueless", guest: "Bagheera")
t3=Ticket.create(theater: "Commando Theater", movie: "Sleepless in Seattle", guest: "Bagheera")
t4=Ticket.create(theater: "Commando Theater", movie: "Rush Hour", guest: "Bagheera")
t5=Ticket.create(theater: "Commando Theater", movie: "The Matrix", guest: "Bagheera")
t6=Ticket.create(theater: "Commando Theater", movie: "Inside Man", guest: "Bagheera")
t7=Ticket.create(theater: "Commando Theater", movie: "Mars Attacks", guest: "Bagheera")
t8=Ticket.create(theater: "Commando Theater", movie: "Predator", guest: "Bagheera")
t9=Ticket.create(theater: "Commando Theater", movie: "Jurassic Park", guest: "Bagheera")
t10=Ticket.create(theater: "Commando Theater", movie: "I Know What You Did Last Summer", guest: "Bagheera")
t11=Ticket.create(theater: "Commando Theater", movie: "Scream", guest: "Bagheera")
t12=Ticket.create(theater: "Commando Theater", movie: "Halloween", guest: "Bagheera")
t13=Ticket.create(theater: "Commando Theater", movie: "Clueless", guest: "Bagheera")
t14=Ticket.create(theater: "Commando Theater", movie: "Clueless", guest: "Bagheera")
t15=Ticket.create(theater: "Commando Theater", movie: "Rush Hour", guest: "Bagheera")
t16=Ticket.create(theater: "Commando Theater", movie: "Jurassic Park", guest: "Bagheera")
t17=Ticket.create(theater: "Commando Theater", movie: "Scream", guest: "Bagheera")
