require_relative '../config/environment'
require 'pry'


Song.create(song_name: "Happy song 01", url: "https://open.spotify.com/track/6ugrRFZUNIpLiqhLUgC7ix?si=piPeOqReRISDiK_HYVPVgA", mood: "Happy")
Song.create(song_name: "Happy song 02", url: "https://open.spotify.com/track/5U9bOxDLTuvHjKqtD3m0Ro?si=kQTiZ7QsRcKUuDKy6n4QIQ", mood: "Happy")
Song.create(song_name: "Happy song 03", url: "https://open.spotify.com/track/7ydeKIGuAdxqkp7OsWGZx6?si=TZ_AUqC8S-aSHIC3wovzrw", mood: "Happy")
Song.create(song_name: "Happy song 04", url: "https://open.spotify.com/track/5qC17VMNoZdF2gAw28FtsV?si=wsAuOGKzTqyR2-4MNjjsow", mood: "Happy")
Song.create(song_name: "Happy song 05", url: "https://open.spotify.com/track/24Jk4wYlLRXI9TUMdkHoMN?si=XExvCF1vQ-SDdn8z7xkj4g", mood: "Happy")
Song.create(song_name: "Happy song 06", url: "https://open.spotify.com/track/299vmLW2iaQxe8y9HLWNiH?si=eW7WYNEbT9qTJw6ogMQotA", mood: "Happy")
Song.create(song_name: "Happy song 07", url: "https://open.spotify.com/track/7qrBYrivpvfXUPBMmqh3dA?si=Qc116wXcSASghQZv1dDCKQ", mood: "Happy")
Song.create(song_name: "Happy song 08", url: "https://open.spotify.com/track/4p5eACHBSDSKxvPrN1Ej5p?si=Pk3XjBXJTjqYJlz8uit51g", mood: "Happy")
Song.create(song_name: "Happy song 09", url: "https://open.spotify.com/track/7pAwFD2HMqGxTnDq8ujxMZ?si=z3K6MRJ4R4WI0r1p-WQFCg", mood: "Happy")
Song.create(song_name: "Happy song 010", url: "https://open.spotify.com/track/0E3x5mJaTkyDbr3r1TKXDm?si=f2phUA5HTtCwO-dfjfX_5g", mood: "Happy")
Song.create(song_name: "Happy song 011", url: "https://open.spotify.com/track/5ZfSRQIWsHaL6j3BhRm1Tq?si=femNpgbOSlmGvqYtQb6IUQ", mood: "Happy")
Song.create(song_name: "Happy song 012", url: "https://open.spotify.com/track/0h7TlF8gKb61aSm874s3cV?si=yi6bXBPsSNeqXf4wPi2lhw", mood: "Happy")
Song.create(song_name: "Happy song 013", url: "https://open.spotify.com/track/2hvjUxoR0UxaiEKcDaRIE6?si=dMLuWANFR9WzqgsOLfSC6A", mood: "Happy")
Song.create(song_name: "Happy song 014", url: "https://open.spotify.com/track/5qZ0z0kNQ4SKt8EHVxgPH8?si=-CMoI-HmQfKT73J51-Alfg", mood: "Happy")
Song.create(song_name: "Happy song 015", url: "https://open.spotify.com/track/4GDaDFJ8j0HB0aHOc5bAb2?si=2js2KtPaRfmiCdhdv512vw", mood: "Happy")
Song.create(song_name: "Happy song 016", url: "https://open.spotify.com/track/566TYVvGGKbV6BIP53VkSn?si=27c7meeoTtaXNwyvXQrijw", mood: "Happy")
Song.create(song_name: "Happy song 017", url: "https://open.spotify.com/track/3pUMsLZIy50bhHOR8K8EKG?si=zVpAwcCYQ7eHIVyxTUXuhQ", mood: "Happy")
Song.create(song_name: "Happy song 018", url: "https://open.spotify.com/track/3RO8tQsiLI0cJFcWGTUZKk?si=4ovmORfiTAa1oSlNmc7gCQ", mood: "Happy")
Song.create(song_name: "Happy song 019", url: "https://open.spotify.com/track/4eOzeeWEKrvU84Nh8c7Nvu?si=K1SdDPCsRiikqsuM1J8YNQ", mood: "Happy")
Song.create(song_name: "Happy song 020", url: "https://open.spotify.com/track/7sIZcntN4MgDOz36jqJV5o?si=aVIfGDGZQmKjWxLXMxjijA", mood: "Happy")
Song.create(song_name: "Happy song 021", url: "https://open.spotify.com/track/0kuTRDo4UHRH1UM9ycnMCh?si=ug2tdST8Q8yVLCmMI_Qfeg", mood: "Happy")
Song.create(song_name: "Happy song 022", url: "https://open.spotify.com/track/629Cjw0fUyZUMkBjnjttDR?si=Fw7ZPsTzSoeaIS18dW51zg", mood: "Happy")
Song.create(song_name: "Happy song 023", url: "https://open.spotify.com/track/5GEfZzWDUTRi5UvOyu1AZq?si=3bHu5AaVRxeOHq-TQHlqEg", mood: "Happy")
Song.create(song_name: "Happy song 024", url: "https://open.spotify.com/track/7lRsXfGnY0PBSxVMIxuHME?si=YKOfLgkyQnGAohSaAane0g", mood: "Happy")
Song.create(song_name: "Happy song 025", url: "https://open.spotify.com/track/6lsY0Qou7uMpOQZnQVqsFp?si=zFyYuZu2QLG10mZgZAdySg", mood: "Happy")
Song.create(song_name: "Happy song 026", url: "https://open.spotify.com/track/6ugrRFZUNIpLiqhLUgC7ix?si=nhQT5InETQGM7gwj5ErKpw", mood: "Happy")
Song.create(song_name: "Happy song 027", url: "https://open.spotify.com/track/4kVmLlBnLcfXIZIIhq3VUq?si=wpSsIo_3RQu5aMJ7-JMXNg", mood: "Happy")
Song.create(song_name: "Happy song 028", url: "https://open.spotify.com/track/0qe0REpyueaBakSU0JA7o9?si=TXSydGqgTpOCK94NEF8YMA", mood: "Happy")
Song.create(song_name: "Happy song 029", url: "https://open.spotify.com/track/0BD9XqvXSSxlHsdBlLKhqA?si=w00POZPfR26hB1KhAHhWQA", mood: "Happy")
Song.create(song_name: "Happy song 030", url: "https://open.spotify.com/track/70AvqwCfLnKMj3HvJDCXyW?si=Wh456oxRTHmd6iRWZ9SbAA", mood: "Happy")
Song.create(song_name: "Happy song 031", url: "https://open.spotify.com/track/7IoVZ7yynM2uKQOTR0s0Ua?si=tM66WK21S8KU8MwdFe7uew", mood: "Happy")
Song.create(song_name: "Happy song 032", url: "https://open.spotify.com/track/6tuZKBiS1p6Ig0UtC0ii0Y?si=PsWZ6EzhTX-n4b-N55j38A", mood: "Happy")
Song.create(song_name: "Happy song 033", url: "https://open.spotify.com/track/4aMQF9lO4bGHrLI66geI8E?si=6VQMFZxiRLqrIza-bu_tmg", mood: "Happy")
Song.create(song_name: "Happy song 035", url: "https://open.spotify.com/track/0gvKmUcc07qNgSjWkGyiAd?si=1FJYlptLSPSS_calbCa2Ag", mood: "Happy")
Song.create(song_name: "Happy song 036", url: "https://open.spotify.com/track/2X2sn7N7HMSB8jKhVP2AJY?si=m49OOivTR2uodeJKGO7TWg", mood: "Happy")
Song.create(song_name: "Happy song 037", url: "https://open.spotify.com/track/5MzB66hfvOvzMuaAz6myLv?si=Vk3o0o7rT4yrRcVqy9Ib4w", mood: "Happy")
Song.create(song_name: "Happy song 038", url: "https://open.spotify.com/track/41hXE5S8D4mRfcdqSMpmAC?si=0ZE0MEH5TgmNg9dXsiZ6vg", mood: "Happy")
Song.create(song_name: "Happy song 039", url: "https://open.spotify.com/track/2RycgtfFQZOPgEGrzBGE0j?si=kPlAnUsvRRyWLWFisOEM2g", mood: "Happy")
Song.create(song_name: "Happy song 040", url: "https://open.spotify.com/track/2COBMrpsGXEagCGkjp2Siz?si=Xy2EKm0ISVqCFtaprm89Uw", mood: "Happy")
Song.create(song_name: "Happy song 041", url: "https://open.spotify.com/track/5cvbog6wen3r3bBbcwL16U?si=j9gXgLXUSvC0Fuuw_xQHHQ", mood: "Happy")
Song.create(song_name: "Happy song 042", url: "https://open.spotify.com/track/6ghICeprXG957CqdLx67WN?si=r1X39YS4ThurpdaHcU9aZg", mood: "Happy")
Song.create(song_name: "Happy song 043", url: "https://open.spotify.com/track/6notNqVa0J99HRgsshef7a?si=eugD2W3YTBGEoP7xdhc2NQ", mood: "Happy")
Song.create(song_name: "Happy song 044", url: "https://open.spotify.com/track/6LdMXBL9RHbXWtZQ8GJCWs?si=xRwXow5wR7WGn_o3GKQq8g", mood: "Happy")
Song.create(song_name: "Happy song 045", url: "https://open.spotify.com/track/4prtutgNrfNcXqXgJvLg0C?si=vfmf355OQGyekhkPh-Gqeg", mood: "Happy")
Song.create(song_name: "Happy song 046", url: "https://open.spotify.com/track/6iiHfPJeO14Z9jRh2wisAG?si=u52GavjcSBK7j0ELtEMpWQ", mood: "Happy")
Song.create(song_name: "Happy song 047", url: "https://open.spotify.com/track/4XTapkMqPyPXi9nkWEggSj?si=zkJjVlSxRsOpiZWHXu-pqg", mood: "Happy")
Song.create(song_name: "Happy song 048", url: "https://open.spotify.com/track/7td13K8PfRT9j2MI6WGwMA?si=S-nsOfggQhSaxNDC9UghPA", mood: "Happy")
Song.create(song_name: "Happy song 049", url: "https://open.spotify.com/track/6oTZJx62mCTt7p3LEqxcT0?si=I_4DBGeUSi6-nf-IE_xkFQ", mood: "Happy")
Song.create(song_name: "Happy song 050", url: "https://open.spotify.com/track/1WMxcpq9RwhJOegfuqesB0?si=byDnoLMnTE2VH8gq0A7wBQ", mood: "Happy")



